### ISSUE TITLE
Component error: cannot import name 'Light' from 'homeassistant.components.light'

### ISSUE THREAD

**Issue by michaelpiron** [michaelpiron/home-assistant-eltako#3]
Upon installation of the custom component, HA returns following error:
![image](https://user-images.githubusercontent.com/4469877/210173824-4094204e-cff0-44aa-bc4f-eb6dcfea2e86.png)

Configuration invalid!
Component error: eltako - cannot import name 'Light' from 'homeassistant.components.light' (/usr/src/homeassistant/homeassistant/components/light/__init__.py)

Error happened in HA Core version 2022.08.01.

**Comment by michaelpiron** [comment]
Work in progress: Fixed the loading of platforms Light, Switch & Cover. See branch created from this issue.

Problem is not yet solved: Now I get this error:
```
2023-01-03 22:10:13.340 INFO (MainThread) [homeassistant.components.cover] Setting up cover.eltako
2023-01-03 22:10:13.342 INFO (MainThread) [homeassistant.components.light] Setting up light.eltako
2023-01-03 22:10:13.342 INFO (MainThread) [homeassistant.components.switch] Setting up switch.eltako
2023-01-03 22:10:13.342 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.eltako


2023-01-03 22:10:13.353 ERROR (MainThread) [eltako] Bus task terminated with 'RS485SerialInterface' object has no attribute 'conn_made', removing main task


2023-01-03 22:10:13.360 ERROR (MainThread) [eltako] 'RS485SerialInterface' object has no attribute 'conn_made'
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/eltakobus/serial.py", line 114, in run
self.suppress_echo = await self.run_echotest()
File "/usr/local/lib/python3.10/site-packages/eltakobus/serial.py", line 72, in run_echotest
await asyncio.wait_for(self.await_bufferlevel(len(echotest)), timeout=0.2, loop=self._loop)
TypeError: wait_for() got an unexpected keyword argument 'loop'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/config/custom_components/eltako/__init__.py", line 120, in bus_done
result = bus_future.result()
File "/usr/local/lib/python3.10/site-packages/eltakobus/serial.py", line 125, in run
self.conn_made.set_exception(e)
AttributeError: 'RS485SerialInterface' object has no attribute 'conn_made'
```

Is there an issue in "**eltakobus**" PyPi package?
Needs further investigation

**Comment by michaelpiron** [comment]
Work in progress: 
I imported chrysn's GitLab repo "eltakobus" (of which the latest version v0.0.7 was published to PyPi) into a new GitHub repo "eltako14bus".
Reason: the GitLab repo seems to be stale. A pull request to resolve a blocking issue is pending since 6 months.

@chrysn, alternatively, I'd be happy to act as a maintainer of your repo (keeping you as the author) to keep it alive. If you prefer that approach, I would join GitLab, and drop my "eltako14bus" repo.

In the meantime: Preparing a v0.0.8, which resolves the issue of a removed _loop_ parameter in asyncio.wait_for coroutine since Python v3.10.

Link: https://github.com/michaelpiron/eltako14bus

**Comment by michaelpiron** [comment]
Further progress: https://github.com/michaelpiron/eltako14bus/issues/3

It seems that my FTS14KS device (I don't have a FAM14) is not being detected properly.
Further followup of this issue in the eltakobus14 repo.
